using System;
using System.Threading.Tasks;
using Microsoft.Maui.Controls;
using Microsoft.Maui.Graphics;
using USJRLedger.Services; // Make sure to use the correct namespace

namespace USJRLedger.Views.Common
{
    public partial class SplashPage : ContentPage
    {
        // Define UI elements that would normally be generated by InitializeComponent
        private StackLayout mainLayout;
        private Image logoImage;
        private Label titleLabel;
        private Label subtitleLabel;
        private ActivityIndicator loadingIndicator;

        public SplashPage()
        {
            // Instead of InitializeComponent(), create the UI programmatically
            CreateUI();
        }

        private void CreateUI()
        {
            try
            {
                // Set page properties
                BackgroundColor = Color.FromRgb(26, 35, 126);  // #1a237e

                // Create main layout
                mainLayout = new StackLayout
                {
                    VerticalOptions = LayoutOptions.Center,
                    HorizontalOptions = LayoutOptions.Center,
                    Spacing = 20
                };

                // Create and add logo image
                logoImage = new Image
                {
                    Source = "splash_logo.png",  // Use the renamed image to avoid duplication
                    HeightRequest = 150,
                    WidthRequest = 150,
                    HorizontalOptions = LayoutOptions.Center
                };
                mainLayout.Children.Add(logoImage);

                // Create and add title label
                titleLabel = new Label
                {
                    Text = "USJR LEDGER",
                    FontSize = 32,
                    FontAttributes = FontAttributes.Bold,
                    TextColor = Colors.White,
                    HorizontalOptions = LayoutOptions.Center,
                    Margin = new Thickness(0, 20, 0, 10)
                };
                mainLayout.Children.Add(titleLabel);

                // Create and add subtitle label
                subtitleLabel = new Label
                {
                    Text = "Organization Management System",
                    FontSize = 18,
                    TextColor = Colors.White,
                    HorizontalOptions = LayoutOptions.Center,
                    Margin = new Thickness(0, 0, 0, 30)
                };
                mainLayout.Children.Add(subtitleLabel);

                // Create and add loading indicator
                loadingIndicator = new ActivityIndicator
                {
                    IsRunning = true,
                    Color = Colors.White,
                    HorizontalOptions = LayoutOptions.Center
                };
                mainLayout.Children.Add(loadingIndicator);

                // Add main layout to page content
                Content = mainLayout;
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error creating UI: {ex.Message}");

                // Fallback to a very basic UI
                Content = new Label
                {
                    Text = "Loading...",
                    TextColor = Colors.White,
                    HorizontalOptions = LayoutOptions.Center,
                    VerticalOptions = LayoutOptions.Center
                };
            }
        }

        protected override async void OnAppearing()
        {
            base.OnAppearing();

            // Simple delay and navigation without animations
            await Task.Delay(3000);

            try
            {
                // Navigate to login page
                await Shell.Current.GoToAsync("//LoginPage");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Navigation error: {ex.Message}");

                // Create a very basic page instead of trying to create a LoginPage with dependencies
                Application.Current.MainPage = new ContentPage
                {
                    BackgroundColor = Colors.White,
                    Content = new VerticalStackLayout
                    {
                        Spacing = 20,
                        Padding = new Thickness(20),
                        VerticalOptions = LayoutOptions.Center,
                        Children =
                        {
                            new Label
                            {
                                Text = "USJR Ledger",
                                FontSize = 24,
                                FontAttributes = FontAttributes.Bold,
                                HorizontalOptions = LayoutOptions.Center
                            },
                            new Label
                            {
                                Text = "Please restart the application",
                                HorizontalOptions = LayoutOptions.Center
                            },
                            new Button
                            {
                                Text = "Exit",
                                HorizontalOptions = LayoutOptions.Center,
                                Command = new Command(() => Environment.Exit(0))
                            }
                        }
                    }
                };
            }
        }
    }
}